# Generated by Django 2.2.3 on 2020-01-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('blood', 'blood'), ('x-ray', 'x-ray'), ('heart', 'heart'), ('sight', 'sight'), ('hear', 'hear'))},
        ),
    ]
