# Generated by Django 2.2.3 on 2020-01-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200101_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(help_text='種類 ex. 抽血', max_length=40),
        ),
    ]
